### ISSUE TITLE
Cannot find module 'xcode' on v2.0.0

### ISSUE THREAD

**Issue by JarikH** [kelvinhokk/cordova-plugin-localization-strings#24]
**This is the full error i'm getting (Cordova v6.3.0):** 

(node:31874) UnhandledPromiseRejectionWarning: Error: Cannot find module 'xcode'
   at Function.Module._resolveFilename (module.js:555:15)
   at Function.Module._load (module.js:482:25)
   at Module.require (module.js:604:17)
   at require (internal/module.js:11:18)
   at module.exports (/Users/{user}/fuse_helperapp/cordova/plugins/cordova-plugin-localization-strings/scripts/create_ios_strings.js:91:17)
   at module.exports (/Users/{user}/fuse_helperapp/cordova/plugins/cordova-plugin-localization-strings/scripts/create_strings.js:11:23)
   at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
   at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
   at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20
   at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
(node:31874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31874) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Anyone else having this issue? Anyone who knows what i'm doing wrong or if something is wrong on the plugins end?**

**Comment by davidefavia** [comment]
Did you run install command with `--fetch` flag? Seems the plugins doesn't find its own dependencies:

`Cannot find module 'xcode'` (first line of your stacktrace)

**Comment by JarikH** [comment]
@davidefavia I'm quite sure that i did do that, but i'll try it again monday, i'll make sure to update you on if it worked or not.

**Comment by JarikH** [comment]
@davidefavia Yeah i just tried to run `cordova plugin add https://github.com/kelvinhokk/cordova-plugin-localization-strings.git --fetch` but it's still giving me the same error, any other things i could try?

**Comment by davidefavia** [comment]
Faced similar issue with `elementtree` module. I removed folders `platforms` and `plugins`, removed `package-lock.json` and installed everything again. Seemed `npm` related, solved thanks to this comment: [npm/npm/issues/17821](https://github.com/npm/npm/issues/17821#issuecomment-346944978)

**Comment by JarikH** [comment]
@davidefavia Thanks, that fixed it 👍
